
Your orders for the next turn are due on Saturday at:

		12:00 noon Universal Time (UTC)
		 = 9:00 AM USA EST
		 = 6:00 AM USA PST

USA players: Please note that the deadline is AM, not PM!  Also, please
format the subject line of your orders as in the following example:

		Subject: FHOrders, Klingon

I generally download orders within an hour of the above deadline.  If they
have not arrived by that time, or if the "Subject:" line is not correctly
formatted, then I will not be able to process them.




