name: Build and Deploy
on:
 push:
   branches:
     - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Build the manual
        run: |
          make manual

      - name: Deploy the manual
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: doc/manual # The folder the action should deploy.
